/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 21 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"

#include "StdH.h"
#include <Engine/Entities/InternalClasses.h>

#include <Engine/Classes/MovableBrushEntity.h>
#include <Engine/Classes/MovableBrushEntity_tables.h>
void CMovableBrushEntity::SetDefaultProperties(void) {
  CMovableEntity::SetDefaultProperties();
}
  void CMovableBrushEntity::DoMoving(void) 
#line 36 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"
{
#line 37 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"
CMovableEntity  :: DoMoving  ();
#line 40 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"
}
  void CMovableBrushEntity::Read_t(CTStream * istr) 
#line 50 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"
{
#line 51 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"
CMovableEntity  :: Read_t  (istr );
#line 52 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"
}
  void CMovableBrushEntity::Write_t(CTStream * ostr) 
#line 55 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"
{
#line 56 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"
CMovableEntity  :: Write_t  (ostr );
#line 57 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"
}
BOOL CMovableBrushEntity::
#line 61 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/MovableBrushEntity.es"
Dummy(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CMovableBrushEntity_Dummy
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CMovableBrushEntity::Dummy expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput; ASSERT(FALSE); return TRUE;};