/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 20 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"

#include "StdH.h"
#include <Engine/Entities/InternalClasses.h>
#include <Engine/Base/Stream.h>
#include <Engine/Base/CRC.h>

#include <Engine/Classes/PlayerEntity.h>
#include <Engine/Classes/PlayerEntity_tables.h>
void CPlayerEntity::SetDefaultProperties(void) {
  en_tmPing = 0.0f;
  CMovableModelEntity::SetDefaultProperties();
}
  CTString CPlayerEntity::GetPlayerName(void) 
#line 42 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{
#line 43 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
return en_pcCharacter  . GetNameForPrinting  ();
#line 44 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
  const CTString & CPlayerEntity::GetName(void)const 
#line 46 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{
#line 47 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
return en_pcCharacter  . GetName  ();
#line 48 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
  INDEX CPlayerEntity::GetMyPlayerIndex(void) 
#line 51 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{
#line 52 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
CEntity  * penMe  = this ;
#line 53 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
if(IsPredictor  ()){
#line 54 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
penMe  = GetPredicted  ();
#line 55 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
#line 56 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
for(INDEX iPlayer  = 0;iPlayer  < GetMaxPlayers  ();iPlayer  ++){
#line 58 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
if(GetPlayerEntity  (iPlayer ) == penMe ){
#line 59 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
return iPlayer ;
#line 60 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
#line 61 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
#line 63 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
return 15;
#line 64 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::DoMoving(void) 
#line 68 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{
#line 69 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: DoMoving  ();
#line 70 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::Copy(CEntity & enOther,ULONG ulFlags) 
#line 74 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{
#line 75 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: Copy  (enOther  , ulFlags );
#line 77 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
CPlayerEntity  * ppenOther  = (CPlayerEntity  *) (& enOther );
#line 78 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
en_pcCharacter  = ppenOther  -> en_pcCharacter ;
#line 79 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
en_plViewpoint  = ppenOther  -> en_plViewpoint ;
#line 80 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
en_plLastViewpoint  = ppenOther  -> en_plLastViewpoint ;
#line 81 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::Read_t(CTStream * istr) 
#line 93 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{
#line 94 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: Read_t  (istr );
#line 95 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
(* istr ) >> en_pcCharacter  >> en_plViewpoint ;
#line 96 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
en_plLastViewpoint  = en_plViewpoint ;
#line 97 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::Write_t(CTStream * ostr) 
#line 100 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{
#line 101 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: Write_t  (ostr );
#line 102 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
(* ostr ) << en_pcCharacter  << en_plViewpoint ;
#line 103 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::ApplyAction(const CPlayerAction & pa,FLOAT tmLatency) {}
  void CPlayerEntity::Disconnect(void) {}
  void CPlayerEntity::CharacterChanged(const CPlayerCharacter & pcNew) {en_pcCharacter  = pcNew ;}
  void CPlayerEntity::GetGameAgentPlayerInfo(INDEX iPlayer,CTString & strOut) {}
  void CPlayerEntity::GetMSLegacyPlayerInf(INDEX iPlayer,CTString & strOut) {}
  void CPlayerEntity::ChecksumForSync(ULONG & ulCRC,INDEX iExtensiveSyncCheck) 
#line 119 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{
#line 120 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: ChecksumForSync  (ulCRC  , iExtensiveSyncCheck );
#line 121 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
CRC_AddBlock  (ulCRC  , en_pcCharacter  . pc_aubGUID  , sizeof  (en_pcCharacter  . pc_aubGUID ));
#line 122 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
CRC_AddBlock  (ulCRC  , en_pcCharacter  . pc_aubAppearance  , sizeof  (en_pcCharacter  . pc_aubAppearance ));
#line 123 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::DumpSync_t(CTStream & strm,INDEX iExtensiveSyncCheck) 
#line 126 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{
#line 127 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: DumpSync_t  (strm  , iExtensiveSyncCheck );
#line 128 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("player: %s\n" , 
#line 129 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
en_pcCharacter  . GetName  ());
#line 130 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("GUID: ");
#line 131 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{for(INDEX i  = 0;i  < sizeof  (en_pcCharacter  . pc_aubGUID );i  ++){
#line 132 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("%02X" , en_pcCharacter  . pc_aubGUID  [ i  ]);
#line 133 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}}
#line 134 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("\n");
#line 135 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("appearance: ");
#line 136 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
{for(INDEX i  = 0;i  < MAX_PLAYERAPPEARANCE ;i  ++){
#line 137 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("%02X" , en_pcCharacter  . pc_aubAppearance  [ i  ]);
#line 138 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}}
#line 139 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("\n");
#line 140 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
}
BOOL CPlayerEntity::
#line 143 "X:/Git/Repos/Serious-Engine/Sources/Engine/Classes/PlayerEntity.es"
Dummy(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPlayerEntity_Dummy
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPlayerEntity::Dummy expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput; ASSERT(FALSE); return TRUE;};